GET http://localhost:3000/alumnos

###
GET http://localhost:3000/alumnos/1002

###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "legajo": 1020,
    "nombre": "Lucía",
    "carrera": "Programación",
    "correo": "lucia@example.com"
}
###
PUT http://localhost:3000/alumnos/22
Content-Type: application/json

{
    "id": 2,
    "nombre": "Juan Perez",
    "carrera": "Programación"
}

###
DELETE http://localhost:3000/alumnos/22

###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id": 5,
    "nombre": "Rocío",
    "carrera": "Programación"
}